name: running-tests

on: push

jobs:
  test-equal-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      SOURCE_IMAGE: romanlamsal/docker-retag-test:test
      TARGET_IMAGE: romanlamsal/docker-retag-test:${{ github.sha }}
    steps:
      # GIVEN
      - uses: actions/checkout@v1
      - name: "Push example image to registry"
        run: |
          docker pull -q alpine:latest
          docker build -t testimage:test -<<EOF
          FROM alpine:latest
          ENV foo=bar
          EOF
          docker tag testimage:test $SOURCE_IMAGE
          docker login -u romanlamsal -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push $SOURCE_IMAGE
          docker image rm $SOURCE_IMAGE
      # WHEN
      - name: "Run action"
        uses: ./
        with:
          source-image: "$SOURCE_IMAGE"
          target-image: "$TARGET_IMAGE"
      # THEN
      - name: "Compare digests"
        run: |
          images_are_equal=$(./compare_digests.sh $SOURCE_IMAGE $TARGET_IMAGE)
          [ "$images_are_equal" = "true" ] || exit 1
  test-non-existing-source-image:
      runs-on: ubuntu-latest
      env:
        TARGET_IMAGE: romanlamsal/docker-retag-test:${{ github.sha }}
      steps:
        - name: "Run action and expect to fail"
          id: "docker-retag"
          uses: ./
          with:
            # WHEN
            source-image: "foo:bar"
            target-image: "$TARGET_IMAGE"
          continue-on-error: true
        # THEN
        - name: "Fail when docker-retag did not fail"
          if: steps.docker-retag.outcome != "failure"
          run: exit 1
